# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BHO2MGB_RainToGauge
                                 A QGIS plugin
 Converts BHO2MGB rainfall grid to propers formats
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-09-01
        copyright            : (C) 2022 by Mino Sorribas
        email                : mino.sorribas@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BHO2MGB_RainToGauge class from file BHO2MGB_RainToGauge.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .bho2mgb_raintogauge import BHO2MGB_RainToGauge
    return BHO2MGB_RainToGauge(iface)
